<?php

require_once '/home/jumonji/temp/mylibrary/php/Util.php';

/**
 * Test class for Util.
 * Generated by PHPUnit on 2012-10-31 at 12:55:50.
 */
class UtilTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testStartsWith().
     */
    public function testStartsWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @dataProvider forTestEndsWith
     */
    public function testEndsWith($haystack, $needle, $bool)
    {
        $ret = Util::endsWith($haystack, $needle);
        $this->assertEquals($ret, $bool);

    }

    /**
     * @todo Implement testMatchesIn().
     */
    public function testMatchesIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function forTestEndsWith()
    {
        return array(
            array("docomo.ne.jp", "docomo.ne.jp", true),
            array("aaa@docomo.ne.jp", "docomo.ne.jp", true),
            array("aaa@docomo.ne.jpa", "docomo.ne.jp", false),
        );
    }
}
?>
